Added hybrid parallel ViLT
hpcaitech/ColossalAI-Examples pull request #29
Opened 2022-02-10 01:23 UTC by ExtremeViscent

An MPI-backended Colossal-AI implementation of Vision-and-Language Transformer using 1D tensor parallel and data parallel.

2022-02-18 07:37 UTC, FrankLeeeee requested changes
Hi, I was trying to run this code, but could not complete. There are some issues in this PR.


`image/vilt/README.md`
1. In the `Prepare Dataset` section, I could not find `write_coco_karpathy` file in the `utils` folder.
2. It will be good if you can prepare a script (e.g. `prepare_dataset.sh` ) for downloading  and converting the dataset. e.g.
```bash

ROOT=$1

cd $ROOT

# download all files
wget http://images.cocodataset.org/zips/train2014.zip
wget http://images.cocodataset.org/zips/val2014.zip
https://cs.stanford.edu/people/karpathy/deepimagesent/caption_datasets.zip

# unzip all files
unzip ...

# converting the dataset
python xxxx.py

```
This will make it easier for other users.

3. In the command section, It will be good to provide an example of using PyTorch Launcher as well since many people may not have MPI installed on their server.
4. I only found `run.py` but not `runcai.py`

`image/vilt/configs.py`
1. in the `parallel` config, it is not needed to specify the data parallel size as it is auto-computed. You can take a look at the [Configure Parallelization | Colossal-AI](https://colossalai.org/tutorials/basics/configure_parallelization).

`image/vilt/run.sh`
1. The `$data_root` seems to assume that data is in a fixed directory relative to the root directory. This may not be so when others are using it. You can ask the user to pass in an argument for the data path.


There are some commented codes in the files as well, do clean them up to avoid confusion to the user.

2022-03-09 03:39 UTC, ExtremeViscent commented
Thank you for reviewing. The commit is edited as requested.

2022-03-29 05:25 UTC, yuxuan-lou approved these changes

2022-03-29 05:34 UTC, yuxuan-lou approved these changes

2022-04-20 07:11 UTC, binmakeswell commented
Hi @ExtremeViscent  Could you cancel the review request for FrankLeeeee? This prevents other reviewers' action.

2022-04-21 02:51 UTC, FrankLeeeee approved these changes

2022-04-21 02:51 UTC, merged